version: '3.8'

services:
  web:
    build: .
    command: uvicorn brick.api.main:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/app
      - /tmp:/tmp
    ports:
      - "8080:8080"
    depends_on:
      - redis

  worker:
    build: .
    command: python celery/worker.py
    volumes:
      - .:/app
      - /tmp:/tmp
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"