# On creating a new release

name: CI/CD Production

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: "Add GitHub to the SSH known hosts file"
      run: |
        mkdir -p -m 0700 /home/runner/.ssh
        echo "${{ secrets.SSH_PRODUCTION_HOST }}" >> /home/runner/.ssh/known_hosts
        chmod 600 /home/runner/.ssh/known_hosts

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRODUCTION_PRIVATE_KEY }}

    - name: Deploy to production server
      run: ssh -o UserKnownHostsFile=/home/runner/.ssh/known_hosts ${{ secrets.SSH_PRODUCTION_SERVER }} 'bash ${{ secrets.SSH_PRODUCTION_PATH }}/scripts/deploy.sh prod ${{ secrets.SSH_PRODUCTION_PATH }} ${{ github.sha }}'
