# Merged pull request from 'dev' into 'main' to stage for release

name: CI/CD Development

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.head_ref == 'dev'
    runs-on: ubuntu-latest

    steps:
    - name: "Add GitHub to the SSH known hosts file"
      run: |
        mkdir -p -m 0700 /home/runner/.ssh
        echo "${{ secrets.SSH_PRODUCTION_HOST }}" >> /home/runner/.ssh/known_hosts
        chmod 600 /home/runner/.ssh/known_hosts

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRODUCTION_PRIVATE_KEY }}

    - name: Deploy to development server
      run: ssh -o UserKnownHostsFile=/home/runner/.ssh/known_hosts ${{ secrets.SSH_PRODUCTION_SERVER }} 'bash ${{ secrets.SSH_DEVELOPMENT_PATH }}/scripts/deploy.sh dev ${{ secrets.SSH_DEVELOPMENT_PATH }} ${{ github.sha }}'
