# On pushing to a new release branch auto version bump is
# performed from latest release, changelog modified, 
# versions modified (cocogitto) and a pull request 
# for merging into main is created

name: CI/CD Release

on:
  push:
    branches:
      - 'release/*' 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Conventional commits check
      uses: oknozor/cocogitto-action@v3
      with:
        check-latest-tag-only: true
    
    - name: Generate release version
      id: release
      run: |
        VERSION=$(cog bump --dry-run --auto)
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Auto bump version and commit
      run: |
        cog bump --auto
        git push origin "release/${{ steps.release.outputs.version }}"
        git push origin "${{ steps.release.outputs.version }}"

    - name: Create PR
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Merge release ${{ steps.release.outputs.version }}'
        title: '[RELEASE] Merge release ${{ steps.release.outputs.version }} into main'
        body: 'This is an automated pull request to merge changes from the release/${{ steps.release.outputs.version }} into main'
        branch: "release/${{ steps.release.outputs.version }}"
        base: main