
name: Test Development Workflow

on:
  push:
    branches:
      - 'test/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'test/')

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        run: sudo service docker start

      - name: Build and Run Tests
        run: docker compose run tests
